### PR TITLE
updated cart UI and fixed padding on marketplace

### PR DESCRIPTION
**Pull request by agul9**

### CODE REVIEW

**Review by Kmittleider — CHANGES_REQUESTED** [review]
The "T" in Total in the cart view is cropped off from my view and there still appears to be some padding on the marketplace page although not a huge amount. Fix up the "T" cropping and maybe take a second look at the marketplace padding - I can help here if you want! But the cardviews look great in the cart!

**Review by josealtron — APPROVED** [review]
Tested and works on my Android phone.

**Review by sohumgala — COMMENTED** [review]
+1 to Katherine's comment, looks great otherwise!

**Review by Kmittleider — APPROVED** [review]
works like a charm! Great work!

**Pull request merged**
